export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_IMMEDIATE = "GET_MOVIES_IMMEDIATE";
export const SET_MOVIES = "SET_MOVIES";
export const GET_MOVIE_ITEM = "GET_MOVIE_ITEM";
export const SET_MOVIE_ITEM = "SET_MOVIE_ITEM";
